FROM apache/airflow:2.9.3-python3.10
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
 
USER airflow
WORKDIR /opt/airflow
 
COPY --chown=airflow:root pyproject.toml ./
COPY --chown=airflow:root src/ ./src/
 
RUN pip install --no-cache-dir .
