FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY src/ ./src/

RUN pip install --no-cache-dir -e .

COPY models/model.pkl ./models/model.pkl

EXPOSE 8000

CMD ["uvicorn", "prodml.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
